### ISSUE TITLE
"no such file or directory, open './secrets.json'" on docker build

### ISSUE THREAD

**Issue by llxxxll** [RossAscends/STMP#12]
```bash
sudo docker compose up --build

[+] Building 0.2s (10/10) FINISHED
 => [stmp internal] load .dockerignore                                                                                                                                            0.0s
 => => transferring context: 2B                                                                                                                                                   0.0s
 => [stmp internal] load build definition from Dockerfile                                                                                                                         0.0s
 => => transferring dockerfile: 170B                                                                                                                                              0.0s
 => [stmp internal] load metadata for docker.io/library/node:20                                                                                                                   0.0s
 => [stmp 1/5] FROM docker.io/library/node:20                                                                                                                                     0.0s
 => [stmp internal] load build context                                                                                                                                            0.0s
 => => transferring context: 39.29kB                                                                                                                                              0.0s
 => CACHED [stmp 2/5] WORKDIR /usr/src/app                                                                                                                                        0.0s
 => CACHED [stmp 3/5] COPY package*.json ./                                                                                                                                       0.0s
 => CACHED [stmp 4/5] RUN npm install --no-audit                                                                                                                                  0.0s
 => [stmp 5/5] COPY . .                                                                                                                                                           0.0s
 => [stmp] exporting to image                                                                                                                                                     0.1s
 => => exporting layers                                                                                                                                                           0.1s
 => => writing image sha256:3538a2f46cf96cb7d1a6ea2c63bb77bd198a14af5a56050933f45c288222eab2                                                                                      0.0s
 => => naming to docker.io/library/util-stmp                                                                                                                                      0.0s
[+] Running 1/0
 ✔ Container SillyTavern_Multiplayer  Recreated                                                                                                                                   0.0s
Attaching to SillyTavern_Multiplayer
SillyTavern_Multiplayer  |
SillyTavern_Multiplayer  | > stmp@1.0.1 start
SillyTavern_Multiplayer  | > node server.js
SillyTavern_Multiplayer  |
SillyTavern_Multiplayer  |
SillyTavern_Multiplayer  | node:fs:453
SillyTavern_Multiplayer  |     return binding.readFileUtf8(path, stringToFlags(options.flag));
SillyTavern_Multiplayer  |                    ^
SillyTavern_Multiplayer  |
SillyTavern_Multiplayer  | Error: ENOENT: no such file or directory, open './secrets.json'
SillyTavern_Multiplayer  |     at Object.readFileSync (node:fs:453:20)
SillyTavern_Multiplayer  |     at Object.<anonymous> (/usr/src/app/src/api-calls.js:24:34)
SillyTavern_Multiplayer  |     at Module._compile (node:internal/modules/cjs/loader:1376:14)
SillyTavern_Multiplayer  |     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
SillyTavern_Multiplayer  |     at Module.load (node:internal/modules/cjs/loader:1207:32)
SillyTavern_Multiplayer  |     at Module._load (node:internal/modules/cjs/loader:1023:12)
SillyTavern_Multiplayer  |     at Module.require (node:internal/modules/cjs/loader:1235:19)
SillyTavern_Multiplayer  |     at require (node:internal/modules/helpers:176:18)
SillyTavern_Multiplayer  |     at Object.<anonymous> (/usr/src/app/server.js:27:13)
SillyTavern_Multiplayer  |     at Module._compile (node:internal/modules/cjs/loader:1376:14) {
SillyTavern_Multiplayer  |   errno: -2,
SillyTavern_Multiplayer  |   code: 'ENOENT',
SillyTavern_Multiplayer  |   syscall: 'open',
SillyTavern_Multiplayer  |   path: './secrets.json'
SillyTavern_Multiplayer  | }
SillyTavern_Multiplayer  |
SillyTavern_Multiplayer  | Node.js v20.10.0
SillyTavern_Multiplayer  |
SillyTavern_Multiplayer exited with code 1
```
so where is the file secrets.json?

**Comment by RossAscends** [comment]
secrets.json will be created by the server when it first runs (or any time it doesn't find the file in the base directory). It's possible the docker file hasn't been updated to reflect this. @city-unit can you check?

**Comment by city-unit** [comment]
I'm not able to replicate this issue. Building the default docker compose file gives me this result:
![image](https://github.com/RossAscends/STMP/assets/140349364/e6734523-920c-489a-b7af-f28c6b87fab4)
The default location of the secrets file is in the same dir as the server and should be created if it doesn't exist per the following: https://github.com/RossAscends/STMP/blob/a7e98510bc3d1ece257ab3ca9c5b07e8d0d322f0/server.js#L154C1-L162

What's the commit hash of the version you're running? @llxxxll
