### ISSUE TITLE
server - Error parsing message: TypeError: fetch failed

### ISSUE THREAD

**Issue by BlankFX1** [RossAscends/STMP#22]
This always appears in the Log after loading the Site.

```
[2024-01-06T18:40:23.747] [ERROR] server - Error parsing message: TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11457:11)
    at async Object.getModelList (B:\STMP\src\api-calls.js:617:22)
    at async WebSocket.<anonymous> (B:\STMP\server.js:660:32) {
  cause: Error: unknown scheme
      at makeNetworkError (node:internal/deps/undici/undici:6802:35)
      at schemeFetch (node:internal/deps/undici/undici:10919:18)
      at node:internal/deps/undici/undici:10792:26
      at mainFetch (node:internal/deps/undici/undici:10809:11)
      at fetching (node:internal/deps/undici/undici:10766:7)
      at fetch2 (node:internal/deps/undici/undici:10644:20)
      at Object.fetch (node:internal/deps/undici/undici:11455:18)
      at fetch (node:internal/process/pre_execution:230:25)
      at Object.getModelList (B:\STMP\src\api-calls.js:617:28)
      at WebSocket.<anonymous> (B:\STMP\server.js:660:42) {
    [cause]: undefined
  }
}
```

If then the user sends a message, the server will just crash.
```
B:\STMP\src\api-calls.js:42
    let isCCSelected = liveAPI.type === 'CC' ? true : false
                               ^

TypeError: Cannot read properties of undefined (reading 'type')
    at Object.getAIResponse (B:\STMP\src\api-calls.js:42:32)
    at handleResponse (B:\STMP\server.js:1026:36)
    at WebSocket.<anonymous> (B:\STMP\server.js:922:25)

Node.js v18.16.0
```
I'm using Text-Generation-Webui on Port 5000.

//Edit: 
It seems to have to do with an wrong saving of the endpoint input.
I input `http://127.0.0.1:5000/v1/` and it will work for the session, but after a server restart, the endpoint will be reset back to `localhost:5000`, even though the correct API Preset is selected.
Correcting the endpoint after each server restart will "fix" the issue.

**Comment by RossAscends** [comment]
this too should be fixed in recent commits.

**Comment by BlankFX1** [comment]
Can't verify as with the most recent update, the Server doesn't even start anymore.
Not even after deleting stmp.db
(I did an git pull to update and it gave no errors.)

```
[2024-01-10T17:13:18.361] [INFO] file - Gathering character card list..
[2024-01-10T17:13:18.399] [WARN] server - No selected character found, getting the latest...
B:\STMP\server.js:253
            liveConfig.promptConfig.selectedCharacter = latestCharacter.char_id;
                                                      ^

TypeError: Cannot set properties of undefined (setting 'selectedCharacter')
    at mainInit (B:\STMP\server.js:253:55)
    at async initFiles (B:\STMP\server.js:268:5)

Node.js v18.16.0
```

**Comment by BlankFX1** [comment]
Nevermind. It got fixed by resetting config.json and setting up the API from scratch.
Can confirm the issue got fixed. Thanks!

**Comment by BlankFX1** [comment]
//Edit: Nevermind. It got fixed by resetting config.json and setting up the API from scratch.
Can confirm the issue got fixed. Thanks!
